dogcollector/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_app.urls')),
]

main_app/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('about/', views.about, name='about'),
    path('dogs/', views.dogs_index, name='index'),
    path('dogs/<int:dog_id>/', views.dogs_detail, name='detail'),
    path('dogs/<int:dog_id>/add_exercise/', views.add_exercise, name='add_exercise'),
    path('dogs/<int:dog_id>/assoc_outfit/<int:outfit_id>/', views.assoc_outfit, name='assoc_outfit'),
    path('dogs/create/', views.DogCreate.as_view(), name='dogs_create'),
    path('dogs/<int:pk>/update/', views.DogUpdate.as_view(), name='dogs_update'),
    path('dogs/<int:pk>/delete/', views.DogDelete.as_view(), name='dogs_delete'),
    path('outfits/', views.OutfitList.as_view(), name='outfits_index'),
    path('outfits/<int:pk>/', views.OutfitDetail.as_view(), name='outfits_detail'),
    path('outfits/create/', views.OutfitCreate.as_view(), name='outfits_create'),
    path('outfits/<int:pk>/update/', views.OutfitUpdate.as_view(), name='outfits_update'),
    path('outfits/<int:pk>/delete/', views.OutfitDelete.as_view(), name='outfits_delete'),
]

main_app/models.py
from django.db import models
from django.urls import reverse

# Create your models here.

class Outfit(models.Model):
    style = models.CharField(max_length=50)
    color = models.CharField(max_length=20)

    def __str__(self):
        return self.style

    def get_absolute_url(self):
        return reverse('outfits_detail', kwargs={'pk': self.id})


class Dog(models.Model):
    name = models.CharField(max_length=100)
    breed = models.CharField(max_length=100)
    description = models.TextField(max_length=250)
    age = models.IntegerField()
    outfits = models.ManyToManyField(Outfit)

    def get_absolute_url(self):
        return reverse('detail', kwargs={'dog_id': self.id})

ACTIVITIES = (
    ('P', 'Park'),
    ('R', 'Run'),
    ('W', 'Walk'),
)

class Exercise(models.Model):
    date = models.DateField('Exercise date')
    activity = models.CharField(
        max_length=1,
        choices=ACTIVITIES,
        default=ACTIVITIES[0][0]
    )

    dog = models.ForeignKey(Dog, on_delete=models.CASCADE)

    class Meta:
        ordering = ['-date']

    def __str__(self):

        return f"{self.get_activity_display()} on {self.date}"

main_app/forms.py
from django.forms import ModelForm
from .models import Exercise

class ExerciseForm(ModelForm):
  class Meta:
    model = Exercise
    fields = ['date', 'activity']

main_app/views.py
from django.shortcuts import render, redirect

from django.views.generic.edit import CreateView, UpdateView, DeleteView
# Create your views here.
from django.views.generic import ListView, DetailView
from django.http import HttpResponse

from .models import Dog, Outfit
from .forms import ExerciseForm

# Define the home view
def assoc_outfit(request, dog_id, outfit_id):
	dog = Dog.objects.get(id=dog_id)
	dog.outfits.add(outfit_id)
	return redirect('detail', dog_id=dog_id)

def home(request):
  return HttpResponse('<h1>Hello /ᐠ｡‸｡ᐟ\ﾉ</h1>')

def about(request):
    return render(request, 'about.html')

def dogs_index(request):
    dogs = Dog.objects.all()
    return render(request, 'dogs/index.html', { 'dogs': dogs })

def dogs_detail(request, dog_id):
    dog = Dog.objects.get(id=dog_id)
    exercise_form = ExerciseForm()
    outfits_dog_doesnt_have = Outfit.objects.exclude(id__in=dog.outfits.all().values_list('id'))
    return render(request, 'dogs/detail.html', {
        'dog': dog,
        'exercise_form': exercise_form,
        'outfits': outfits_dog_doesnt_have
        })

class DogCreate(CreateView):
  model = Dog
  fields = ['name', 'breed', 'description', 'age']

class DogUpdate(UpdateView):
  model = Dog
  # Let's disallow the renaming of a cat by excluding the name field!
  fields = ['breed', 'description', 'age']

class DogDelete(DeleteView):
  model = Dog
  success_url = '/dogs/'

def add_exercise(request, dog_id):
  form = ExerciseForm(request.POST)
  if form.is_valid():
      new_exercise = form.save(commit=False)
      new_exercise.dog_id = dog_id
      new_exercise.save()
  return redirect('detail', dog_id=dog_id)

class OutfitList(ListView):
    model = Outfit


class OutfitDetail(DetailView):
    model = Outfit


class OutfitCreate(CreateView):
    model = Outfit
    fields = '__all__'


class OutfitUpdate(UpdateView):
    model = Outfit
    fields = ['style', 'color']


class OutfitDelete(DeleteView):
    model = Outfit
    success_url = '/outfits/'

main_app/templates/about.html
{% extends 'base.html' %}
{% block content %}

<h1>About the Dog Collector</h1>
<hr />
<p>Hire the Dog Collector!</p>

{% endblock %}

main_app/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Dog Collector</title>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
  <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
  <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
</head>
<body>
  <header class="navbar-fixed">
    <nav>
      <div class="nav-wrapper">
        <ul>
          <li><a href="/" class="left brand-logo">&nbsp;&nbsp;DogCollector</a></li>
        </ul>
        <ul class="right">
            <li><a href="{% url 'about' %}">About</a></li>
            <li><a href="{% url 'outfits_create' %}">Add an Outfit</a></li>
            <li><a href="{% url 'outfits_index' %}">View All Outfits</a></li>
            <li><a href="{% url 'dogs_create' %}">Add a Dog</a></li>
            <li><a href="{% url 'index' %}">View All My Dogs</a></li>
        </ul>
      </div>
    </nav>
  </header>
  <main class="container">
    {% block content %}
    {% endblock %}
  </main>
  <footer class="page-footer">
    <div class="right">All Rights Reserved, &copy; 2022 Dog Collector &nbsp;</div>
  </footer>
</body>
</html>

main_app/templates/dogs/detail.html
{% extends 'base.html' %}
{% block content %}

<h1>Dog Details</h1>

<div class="row">
  <div class="col s6">
    <div class="card">
      <div class="card-content">
        <span class="card-title">{{ dog.name }}</span>
        <p>Breed: {{ dog.breed }}</p>
        <p>Description: {{ dog.description }}</p>
        {% if dog.age > 0 %}
          <p>Age: {{ dog.age }}</p>
        {% else %}
          <p>Age: Puppy</p>
        {% endif %}
      </div>
      <div class="card-action">
        <a href="{% url 'dogs_update' dog.id %}">Edit</a>
        <a href="{% url 'dogs_delete' dog.id %}">Delete</a>
      </div>
    </div>
  </div>
  <div class="col s6">
    <form method="post" action="{% url 'add_exercise' dog.id %}">
        {% csrf_token %}
        {{ exercise_form.as_p }}
        <input type="submit" class="btn" value="Add Exercise">
      </form>
    <table class="striped">
      <thead>
        <tr><th>Date</th><th>Activity</th></tr>
      </thead>
      <tbody>
        {% for exercise in dog.exercise_set.all %}
          <tr>
            <td>{{exercise.date}}</td>
            <td>{{exercise.get_activity_display}}</td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
</div>

<hr />
<div class="row">
  <div class="col s6">
    <h3>{{ dog.name }}'s Outfits</h3>
    {% if dog.outfits.count %}
      {% for outfit in dog.outfits.all %}
        <div class="card">
          <div class="card-content">
            <span class="card-title">
              A <span style="color: {{ outfit.color }}">{{ outfit.color }}</span> {{ outfit.style }}
            </span>
          </div>
        </div>
      {% endfor %}
    {% else %}
      <h5>No Cute Outfits Yet :(</h5>
    {% endif %}
  </div>

  <div class="col s6">
    <h3>Lets Go Shopping</h3>
    {% if outfits.count %}
      {% for outfit in outfits.all %}
        <div class="card">
          <div class="card-content">
            <span class="card-title">
              A <span style="color: {{ outfit.color }}">{{ outfit.color }}</span> {{ outfit.style }}
            </span>
          </div>
          <div class="card-action">
            <form action="{% url 'assoc_outfit' dog.id outfit.id %}" method="post">
              {% csrf_token %}
              <button type="submit" class="btn">Add</button>
            </form>
          </div>
        </div>
      {% endfor %}
    {% else %}
      <h5>{{dog.name}} has so many clothes!</h5>
    {% endif %}
  </div>
</div>

<script>
    const dateEl = document.querySelector('#id_date');
    M.Datepicker.init(dateEl, {
      format: 'yyyy-mm-dd',
      defaultDate: new Date(),
      setDefaultDate: true,
      autoClose: true
    })

    const selectEl = document.getElementById('id_activity')
    M.FormSelect.init(selectEl)
  </script>
{% endblock %}

main_app/templates/dogs/index.html
{% extends 'base.html' %}
{% block content %}

<h1>Dog List</h1>

{% for dog in dogs %}
  <div class="card">
    <a href="{% url 'detail' dog.id %}">
    <div class="card-content">
      <span class="card-title">{{ dog.name }}</span>
      <p>Breed: {{ dog.breed }}</p>
    </div>
    </a>
  </div>
{% endfor %}

{% endblock %}

main_app/templates/main_app/dog_confirm_delete.html
{% extends 'base.html' %}

{% block content %}
  <h1>Delete Dog</h1>

  <h4>Are you sure you want to delete <span class="teal-text">{{ object.name }}</span>?</h4>

  <form action="" method="POST">
    {% csrf_token %}
    <input type="submit" value="Yes - Delete!" class="btn">
    <a href="{% url 'detail' dog.id %}">Cancel</a>
  </form>
{% endblock %}

main_app/templates/main_app/dog_form.html
{% extends 'base.html' %}

{% block content %}
{% if object %}
    <h1>Edit <span class="teal-text">{{object.name}}</span></h1>
  {% else %}
    <h1>Add Dog</h1>
  {% endif %}
  <!-- Leaving the action empty makes the form post to the same url used to display it -->
  <form action="" method="post">
    <!-- Django requires the following for security purposes -->
    {% csrf_token %}
    <table>
      <!-- Render the inputs inside of <tr>s & <td>s -->
      {{ form.as_table }}
    </table>
    <input type="submit" value="Submit!" class="btn">
  </form>
{% endblock %}

main_app/templates/main_app/outfit_confirm_delete.html
{% extends 'base.html' %}

{% block content %}
  <h1>Delete Outfit</h1>

  <h4>Are you sure you want to delete <span class="teal-text">{{ object.style }}</span>?</h4>

  <form action="" method="POST">
    {% csrf_token %}
    <input type="submit" value="Yes - Delete!" class="btn">
    <a href="{% url 'outfits_detail' object.id %}">Cancel</a>
  </form>
{% endblock %}

main_app/templates/main_app/outfit_detail.html
{% extends 'base.html' %}
{% block content %}

<h1>Outfit Details</h1>

<div class="row">
  <div class="col s6 col-offset-3">
    <div class="card">
      <div class="card-content">
        <span class="card-title">{{ outfit.style }}</span>
        <p>Color: {{ outfit.color }}</p>
      </div>
      <div class="card-action">
        <a href="{% url 'outfits_update' outfit.id %}">Edit</a>
        <a href="{% url 'outfits_delete' outfit.id %}">Delete</a>
      </div>
    </div>
  </div>
</div>
{% endblock %}

main_app/templates/main_app/outfit_form.html
{% extends 'base.html' %}

{% block content %}
  {% if object %}
    <h1>Edit <span class="teal-text">{{object.style}}</span></h1>
  {% else %}
    <h1>Add Outfit</h1>
  {% endif %}
  <!-- Leaving the action empty makes the form post to the same url used to display it -->
  <form action="" method="post">
    <!-- Django requires the following for security purposes -->
    {% csrf_token %}
    <table>
      <!-- Render the inputs inside of <tr>s & <td>s -->
      {{ form.as_table }}
    </table>
    <input type="submit" value="Submit!" class="btn">
  </form>
{% endblock %}

main_app/templates/main_app/outfit_list.html
{% extends 'base.html' %}
{% block content %}

<h1>Outfit List</h1>

{% for outfit in outfit_list %}
  <a href="{% url 'outfits_detail' outfit.id %}">
    <div class="card">
        <div class="card-content">
            <span class="card-title">{{ outfit.style }}</span>
            <p>Color: {{ outfit.color }}</p>
        </div>
    </div>
  </a>
{% endfor %}

{% endblock %}